Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-02, with the labels that each got.

#55 Fix database cleaner config
  spec/support/database_cleaner.rb
Labels: bug

#51 Implement defra ruby validators (company no.)
  Gemfile.lock
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/registration_number_form.rb
  app/services/waste_exemptions_engine/companies_house_service.rb
  app/validators/waste_exemptions_engine/company_no_validator.rb
  lib/waste_exemptions_engine.rb
  lib/waste_exemptions_engine/engine.rb
  waste_exemptions_engine.gemspec
Labels: bug

#52 Fix issues with company no. validation
  app/forms/waste_exemptions_engine/registration_number_form.rb
  spec/factories/forms/registration_number_form.rb
  spec/factories/transient_registration.rb
  spec/forms/waste_exemptions_engine/registration_number_form_spec.rb
Labels: bug

#53 Make choose exemptions checkboxes more accessible
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  spec/factories/exemption.rb
  spec/factories/forms/exemptions_form.rb
  spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
Labels: enhancement

#57 Fix our simplecov configuration
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/simplecov.rb
Labels: bug

#56 Handle refresh on the completion page
  app/controllers/waste_exemptions_engine/forms_controller.rb
  spec/controllers/waste_exemptions_engine/forms_controller_spec.rb
Labels: bug

#58 Remove rspec use transaction fixtures config
  spec/rails_helper.rb
Labels: housekeeping

#59 Include url helpers in request specs
  spec/rails_helper.rb
Labels: housekeeping

#62 Inherit authorisation/authentication preferences from host
  app/controllers/waste_exemptions_engine/application_controller.rb
Labels: bug

#66 Form widths classes added to relevant views
  app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
  app/views/waste_exemptions_engine/applicant_phone_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_phone_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
  app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
  app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
Labels: enhancement

#60 Fix transpose farm answers in check answers page
  app/controllers/waste_exemptions_engine/is_a_farm_forms_controller.rb
  app/controllers/waste_exemptions_engine/is_a_farmer_forms_controller.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/is_a_farmer_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb
  app/views/waste_exemptions_engine/is_a_farm_forms/new.html.erb
  app/views/waste_exemptions_engine/is_a_farmer_forms/new.html.erb
  config/locales/forms/check_your_answers_forms/en.yml
  config/locales/forms/is_a_farmer_forms/en.yml
  config/locales/forms/on_a_farm_forms/en.yml
  config/routes.rb
  db/migrate/20190205230038_rename_on_a_farm_to_is_a_farmer.rb
  db/migrate/20190205234300_rename_is_a_farm_to_on_a_farm.rb
  spec/dummy/db/schema.rb
Labels: bug

#68 Tag rspecs that use VCR
  spec/validators/waste_exemptions_engine/postcode_validator_spec.rb
Labels: housekeeping

#70 Add address form tests
  app/forms/waste_exemptions_engine/address_lookup_form.rb
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/models/waste_exemptions_engine/transient_address.rb
  spec/factories/forms/contact_address_lookup_form.rb
  spec/factories/forms/contact_address_manual_form.rb
  spec/factories/forms/operator_address_lookup_form.rb
  spec/factories/forms/operator_address_manual_form.rb
  spec/factories/forms/site_address_lookup_form.rb
  spec/factories/forms/site_address_manual_form.rb
  spec/forms/waste_exemptions_engine/contact_address_lookup_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_address_manual_form_spec.rb
  spec/forms/waste_exemptions_engine/operator_address_lookup_form_spec.rb
  spec/forms/waste_exemptions_engine/operator_address_manual_form_spec.rb
  spec/forms/waste_exemptions_engine/site_address_lookup_form_spec.rb
  spec/forms/waste_exemptions_engine/site_address_manual_form_spec.rb
  spec/support/shared_examples/forms/address_lookup_form.rb
  spec/support/shared_examples/forms/address_manual_form.rb
  spec/support/shared_examples/forms/validated_form.rb
Labels: housekeeping

#76 Refactor the AddressManualForm validation
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/validators/waste_exemptions_engine/manual_address_validator.rb
  spec/dummy/config/locales/manual_address_validator/en.yml
  spec/support/shared_examples/forms/address_manual_form.rb
  spec/validators/waste_exemptions_engine/manual_address_validator_spec.rb
Labels: housekeeping

#78 Add missing label text for person name form partial
  config/locales/partials/person_name.en.yml
Labels: bug

#75 Add remaining form tests
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  app/views/waste_exemptions_engine/applicant_email_forms/new.html.erb
  config/locales/forms/applicant_email_forms/en.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/factories/forms/applicant_email_form.rb
  spec/factories/forms/applicant_name_form.rb
  spec/factories/forms/applicant_phone_form.rb
  spec/factories/forms/business_type_form.rb
  spec/factories/forms/check_your_answers_form.rb
  spec/factories/forms/contact_email_form.rb
  spec/factories/forms/contact_name_form.rb
  spec/factories/forms/contact_phone_form.rb
  spec/factories/forms/contact_position_form.rb
  spec/factories/forms/declaration_form.rb
  spec/factories/forms/is_a_farmer_form.rb
  spec/factories/forms/location_form.rb
  spec/factories/forms/main_people_form.rb
  spec/factories/forms/on_a_farm_form.rb
  spec/factories/forms/operator_name_form.rb
  spec/factories/forms/site_grid_reference_form.rb
  spec/factories/forms/start_form.rb
  spec/forms/waste_exemptions_engine/applicant_email_form_spec.rb
  spec/forms/waste_exemptions_engine/applicant_name_form_spec.rb
  spec/forms/waste_exemptions_engine/applicant_phone_form_spec.rb
  spec/forms/waste_exemptions_engine/business_type_form_spec.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_email_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_name_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_phone_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_position_form_spec.rb
  spec/forms/waste_exemptions_engine/declaration_form_spec.rb
  spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
  spec/forms/waste_exemptions_engine/is_a_farmer_form_spec.rb
  spec/forms/waste_exemptions_engine/location_form_spec.rb
  spec/forms/waste_exemptions_engine/main_people_form_spec.rb
  spec/forms/waste_exemptions_engine/on_a_farm_form_spec.rb
  spec/forms/waste_exemptions_engine/operator_name_form_spec.rb
  spec/forms/waste_exemptions_engine/operator_postcode_form_spec.rb
  spec/forms/waste_exemptions_engine/registration_number_form_spec.rb
  spec/forms/waste_exemptions_engine/site_grid_reference_form_spec.rb
  spec/forms/waste_exemptions_engine/site_postcode_form_spec.rb
  spec/forms/waste_exemptions_engine/start_form_spec.rb
  spec/support/shared_examples/forms/postcode_form.rb
  spec/validators/waste_exemptions_engine/position_validator_spec.rb
Labels: housekeeping

#82 Alias transient_registration associations to non-transient names
  app/models/waste_exemptions_engine/transient_registration.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: enhancement

#83 Fix order dependence in ExemptionsForm spec
  spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
Labels: housekeeping

#84 Override methods for submitting dead-end forms
  app/controllers/waste_exemptions_engine/register_in_northern_ireland_forms_controller.rb
  app/controllers/waste_exemptions_engine/register_in_scotland_forms_controller.rb
  app/controllers/waste_exemptions_engine/register_in_wales_forms_controller.rb
  app/forms/waste_exemptions_engine/register_in_northern_ireland_form.rb
  app/forms/waste_exemptions_engine/register_in_scotland_form.rb
  app/forms/waste_exemptions_engine/register_in_wales_form.rb
Labels: housekeeping

#81 Add models tests
  app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  spec/factories/address.rb
  spec/factories/person.rb
  spec/factories/registration.rb
  spec/factories/registration_exemption.rb
  spec/factories/transient_address.rb
  spec/factories/transient_registration_exemption.rb
  spec/models/waste_exemptions_engine/address_spec.rb
  spec/models/waste_exemptions_engine/exemption_spec.rb
  spec/models/waste_exemptions_engine/person_spec.rb
  spec/models/waste_exemptions_engine/registration_exemption_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/models/waste_exemptions_engine/transient_address_spec.rb
  spec/models/waste_exemptions_engine/transient_person_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_exemption_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_spec.rb
  spec/support/helpers/model_properties.rb
  spec/support/shared_examples/models/changer_of_the_exemption_status.rb
  spec/support/shared_examples/models/owner_of_registration_attributes.rb
Labels: housekeeping
