Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-08, with the labels that each got.

#248 Pre-populate RenewRegistration with the correct registration data
  app/controllers/waste_exemptions_engine/forms_controller.rb
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
  app/models/waste_exemptions_engine/edit_registration.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  app/services/waste_exemptions_engine/renewal_start_service.rb
  db/migrate/20190801095905_remove_transient_registrations_regerence_index.rb
  spec/dummy/db/schema.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/edit_registration_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_spec.rb
  spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
  spec/services/waste_exemptions_engine/renewal_start_service_spec.rb
  spec/support/shared_examples/models/transient_registration.rb
Labels: enhancement

#253 Fixes to renew token workflow
  app/controllers/concerns/waste_exemptions_engine/can_redirect_form_to_correct_path.rb
  app/controllers/waste_exemptions_engine/forms_controller.rb
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
  app/views/waste_exemptions_engine/renews/new.html.erb
  spec/requests/waste_exemptions_engine/renew_spec.rb
Labels: enhancement

#252 Add content to 'renew with changes' page
  app/views/waste_exemptions_engine/renew_with_changes_forms/new.html.erb
  config/locales/forms/renew_with_changes_forms/en.yml
Labels: enhancement

#256 Add options to renewal start page
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  app/views/waste_exemptions_engine/renewal_start_forms/new.html.erb
  config/locales/forms/renewal_start_forms/en.yml
  db/migrate/20190801171410_add_temp_renew_without_changes_to_transient_registration.rb
  spec/dummy/db/schema.rb
  spec/forms/waste_exemptions_engine/renewal_start_form_spec.rb
  spec/requests/waste_exemptions_engine/renewal_start_forms_spec.rb
  spec/support/helpers/model_properties.rb
Labels: enhancement

#257 Make a minor content amend to 'renew with changes' page
  config/locales/forms/renew_with_changes_forms/en.yml
Labels: enhancement

#254 Make it possible to use ENV variables in feature toggles
  .travis.yml
  app/models/waste_exemptions_engine/feature_toggle.rb
  spec/dummy/config/feature_toggles.yml
  spec/models/waste_exemptions_engine/feature_toggle_spec.rb
  spec/rails_helper.rb
Labels: enhancement

#258 Use has_secure_token for magic link renew token
  Gemfile.lock
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/waste_exemptions_engine/concerns/can_process_jwt_tokens.rb
  app/services/waste_exemptions_engine/generate_renew_token_service.rb
  app/services/waste_exemptions_engine/validate_authenticity_of_renew_token_service.rb
  spec/requests/waste_exemptions_engine/renew_spec.rb
  spec/services/waste_exemptions_engine/generate_renew_token_service_spec.rb
  spec/services/waste_exemptions_engine/validate_authenticity_of_renew_token_service_spec.rb
  spec/support/helpers/generate_renew_token.rb
  waste_exemptions_engine.gemspec
Labels: enhancement

#259 Add missing W3C validation tests
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec.yml
  spec/cassettes/w3c_valid_content/errors_spec.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/start_forms_spec.yml
  spec/requests/waste_exemptions_engine/confirm_edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_forms_spec.rb
  spec/requests/waste_exemptions_engine/errors_spec.rb
  spec/requests/waste_exemptions_engine/renew_with_changes_forms_spec.rb
  spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/start_forms_spec.rb
Labels: housekeeping

#261 Apply path fix to mailer helper
  app/helpers/waste_exemptions_engine/mailer_helper.rb
Labels: bug

#260 Make it possible to jump directly into the declaration page at renewal
  app/controllers/waste_exemptions_engine/renew_without_changes_forms_controller.rb
  app/forms/waste_exemptions_engine/renew_without_changes_form.rb
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  app/views/waste_exemptions_engine/renew_without_changes_forms/new.html.erb
  config/locales/forms/renew_without_changes_forms/en.yml
  config/routes.rb
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec.yml
  spec/factories/forms/renewal_without_changes_form.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/declaration_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renew_without_changes_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_start_form_spec.rb
  spec/requests/waste_exemptions_engine/renew_without_changes_forms_spec.rb
Labels: enhancement

#262 Style renew without changes page
  app/views/waste_exemptions_engine/renew_without_changes_forms/new.html.erb
  config/locales/forms/renew_without_changes_forms/en.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec.yml
Labels: enhancement

#263 Record referring registration when renewing
  app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  db/migrate/20190805152649_add_referring_registration_id_to_registrations.rb
  spec/dummy/db/schema.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/renewing_registration_spec.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
  spec/support/shared_examples/models/transient_registration.rb
Labels: enhancement

#264 Prevent user to renew again
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/helpers/waste_exemptions_engine/renews_helper.rb
  app/views/waste_exemptions_engine/renews/already_renewed.html.erb
  config/locales/forms/renews/en.yml
  spec/cassettes/w3c_valid_content/renew_spec.yml
  spec/requests/waste_exemptions_engine/renew_spec.rb
Labels: enhancement

#267 Redirect to correct site address form on Renewing
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/is_a_farmer_form_spec.rb
Labels: enhancement

#265 Make post-QA fixes on 'about to renew' page
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/views/waste_exemptions_engine/renewal_start_forms/new.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_applicant.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_contact.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_exemptions.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_farming.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_location.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_operator.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_site.html.erb
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec.yml
Labels: bug

#266 Implement design of Renew completed page
  app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
  app/forms/waste_exemptions_engine/renewal_complete_form.rb
  app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
  config/initializers/time_formats.rb
  config/locales/forms/renewal_complete_forms/en.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec.yml
  spec/factories/registration_exemption.rb
Labels: enhancement

#270 Fix broken validation message links
  app/views/waste_exemptions_engine/shared/_errors.html.erb
Labels: bug

#271 Fix bug on renewal creation
  app/models/waste_exemptions_engine/renewing_registration.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
Labels: bug

#272 Fix bug on site address workflow for renewal
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/check_your_answers_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/site_postcode_form_spec.rb
Labels: bug

#273 Add default ordering to registration exemptions
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/models/waste_exemptions_engine/transient_registration_exemption.rb
Labels: enhancement

#277 Add custom error page on missing token
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/helpers/waste_exemptions_engine/renews_helper.rb
  app/views/waste_exemptions_engine/renews/already_renewed.html.erb
  app/views/waste_exemptions_engine/renews/invalid_magic_link.html.erb
  config/locales/forms/renews/en.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/requests/waste_exemptions_engine/renew_spec.rb
Labels: enhancement

#275 Don't use default scope to order registration exemptions
  app/forms/waste_exemptions_engine/data_overview_form.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/models/waste_exemptions_engine/transient_registration_exemption.rb
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_exemptions.html.erb
Labels: bug

#279 Optimise query to appease Bullet
  app/forms/waste_exemptions_engine/data_overview_form.rb
Labels: housekeeping

#278 Remove unnecessary data after business type change
  app/services/waste_exemptions_engine/registration_completion_service.rb
  spec/factories/new_registration.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
Labels: enhancement

#282 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec/GET-confirm_edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec/GET-edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec/GET-edit_complete_form.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec/when-WasteExemptionsEngine-configuration-edit_enabled-is-true-.yml
  spec/cassettes/w3c_valid_content/errors_spec/-show.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/location_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec/GET-renew_with_changes_form.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec/GET-renew_without_changes_form.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/start_forms_spec/GET-start_form.yml
Labels: housekeeping

#283 Capitalise env var in feature toggle test
  spec/models/waste_exemptions_engine/feature_toggle_spec.rb
Labels: bug

#274 Display error when trying to renew too late
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/waste_exemptions_engine/registration.rb
  app/views/waste_exemptions_engine/renews/past_renewal_window.html.erb
  config/locales/forms/renews/en.yml
  lib/waste_exemptions_engine.rb
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/dummy/config/initializers/waste_exemptions_engine.rb
  spec/factories/registration.rb
  spec/factories/registration_exemption.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/requests/waste_exemptions_engine/renew_spec.rb
Labels: enhancement

#285 Copy changes to registration forms
  config/locales/forms/applicant_email_forms/en.yml
  config/locales/forms/applicant_name_forms/en.yml
  config/locales/forms/applicant_phone_forms/en.yml
  config/locales/forms/contact_address_lookup_forms/en.yml
  config/locales/forms/contact_address_manual_forms/en.yml
  config/locales/forms/contact_email_forms/en.yml
  config/locales/forms/contact_phone_forms/en.yml
  config/locales/forms/contact_position_forms/en.yml
  config/locales/forms/contact_postcode_forms/en.yml
  config/locales/forms/is_a_farmer_forms/en.yml
  config/locales/forms/location_forms/en.yml
  config/locales/forms/register_in_northern_ireland_forms/en.yml
  config/locales/forms/register_in_scotland_forms/en.yml
  config/locales/forms/register_in_wales_forms/en.yml
  config/locales/forms/registration_number_forms/en.yml
  config/locales/forms/renews/en.yml
  config/locales/forms/site_address_lookup_forms/en.yml
  config/locales/forms/site_address_manual_forms/en.yml
  config/locales/forms/site_postcode_forms/en.yml
Labels: enhancement

#290 Fix past_renewal_window? to not drop one day
  app/models/waste_exemptions_engine/registration.rb
  spec/dummy/db/schema.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: bug

#291 Amend text on 'too late to renew' page
  config/locales/forms/renews/en.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
Labels: enhancement

#289 Add settings to use parallel testing on Travis
  .travis.yml
  Gemfile.lock
  Rakefile
  spec/dummy/config/database.travis.yml
  waste_exemptions_engine.gemspec
Labels: housekeeping

#292 Add missin translation for LLP
  config/locales/forms/operator_name_forms/en.yml
Labels: bug

#287 Add test coverage on edit and renewal transient registrations
  spec/factories/edit_registration.rb
  spec/factories/forms/applicant_email_form.rb
  spec/factories/forms/applicant_name_form.rb
  spec/factories/forms/applicant_phone_form.rb
  spec/factories/forms/business_type_form.rb
  spec/factories/forms/contact_email_form.rb
  spec/factories/forms/contact_name_form.rb
  spec/factories/forms/contact_phone_form.rb
  spec/factories/forms/contact_position_form.rb
  spec/factories/forms/contact_postcodes_form.rb
  spec/factories/forms/operator_name_form.rb
  spec/factories/forms/operator_postcodes_form.rb
  spec/factories/forms/site_grid_reference_form.rb
  spec/factories/forms/site_postcodes_form.rb
  spec/factories/renewing_registration.rb
  spec/requests/waste_exemptions_engine/applicant_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_grid_reference_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_postcode_forms_spec.rb
Labels: housekeeping

#288 Remove second token setting on forms
  app/forms/waste_exemptions_engine/address_lookup_form.rb
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/applicant_name_form.rb
  app/forms/waste_exemptions_engine/applicant_phone_form.rb
  app/forms/waste_exemptions_engine/base_form.rb
  app/forms/waste_exemptions_engine/business_type_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/confirm_edit_cancelled_form.rb
  app/forms/waste_exemptions_engine/contact_email_form.rb
  app/forms/waste_exemptions_engine/contact_name_form.rb
  app/forms/waste_exemptions_engine/contact_phone_form.rb
  app/forms/waste_exemptions_engine/contact_position_form.rb
  app/forms/waste_exemptions_engine/declaration_form.rb
  app/forms/waste_exemptions_engine/edit_form.rb
  app/forms/waste_exemptions_engine/exemptions_form.rb
  app/forms/waste_exemptions_engine/is_a_farmer_form.rb
  app/forms/waste_exemptions_engine/location_form.rb
  app/forms/waste_exemptions_engine/on_a_farm_form.rb
  app/forms/waste_exemptions_engine/operator_name_form.rb
  app/forms/waste_exemptions_engine/person_form.rb
  app/forms/waste_exemptions_engine/postcode_form.rb
  app/forms/waste_exemptions_engine/registration_number_form.rb
  app/forms/waste_exemptions_engine/renew_with_changes_form.rb
  app/forms/waste_exemptions_engine/renew_without_changes_form.rb
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  app/forms/waste_exemptions_engine/start_form.rb
Labels: housekeeping

#293 Use validation gem for business type
  app/forms/waste_exemptions_engine/business_type_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/validators/waste_exemptions_engine/business_type_validator.rb
  spec/forms/waste_exemptions_engine/business_type_form_spec.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/validators/waste_exemptions_engine/business_type_validator_spec.rb
Labels: housekeeping

#294 Only display type-dependant data when required
  app/forms/waste_exemptions_engine/data_overview_form.rb
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/renewal_start_form_spec.rb
  spec/support/shared_examples/forms/data_overview_form.rb
Labels: bug

#295 Use validation gem for emails
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_email_form.rb
  app/validators/waste_exemptions_engine/email_validator.rb
  spec/forms/waste_exemptions_engine/applicant_email_form_spec.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_email_form_spec.rb
  spec/validators/waste_exemptions_engine/email_validator_spec.rb
Labels: housekeeping

#296 Use validation gem for grid reference
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  app/validators/waste_exemptions_engine/grid_reference_validator.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/site_grid_reference_form_spec.rb
  spec/validators/waste_exemptions_engine/grid_reference_validator_spec.rb
Labels: housekeeping

#297 Use validation gem for location
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/location_form.rb
  app/validators/waste_exemptions_engine/location_validator.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/location_form_spec.rb
  spec/validators/waste_exemptions_engine/location_validator_spec.rb
Labels: housekeeping

#298 Change re-register to renew
  config/locales/forms/start_forms/en.yml
Labels: enhancement

#299 Use validation gem for phone numbers
  app/forms/waste_exemptions_engine/applicant_phone_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_phone_form.rb
  app/validators/waste_exemptions_engine/phone_number_validator.rb
  spec/forms/waste_exemptions_engine/applicant_phone_form_spec.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_phone_form_spec.rb
  spec/validators/waste_exemptions_engine/phone_number_validator_spec.rb
Labels: housekeeping

#301 Use validation gem for token
  app/forms/waste_exemptions_engine/base_form.rb
  app/validators/waste_exemptions_engine/token_validator.rb
  spec/validators/waste_exemptions_engine/token_validator_spec.rb
Labels: housekeeping

#300 Use validation gem for contact position
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_position_form.rb
  app/validators/waste_exemptions_engine/position_validator.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_position_form_spec.rb
  spec/validators/waste_exemptions_engine/position_validator_spec.rb
Labels: housekeeping

#302 Check for HTML-escaped strings in request tests
  spec/requests/waste_exemptions_engine/applicant_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_grid_reference_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_postcode_forms_spec.rb
  spec/support/html_matchers.rb
Labels: housekeeping

#303 Copy expired registrations to RenewingRegistration
  app/models/concerns/waste_exemptions_engine/can_copy_data_from_registration.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  spec/factories/registration.rb
  spec/models/waste_exemptions_engine/edit_registration_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_spec.rb
Labels: bug

#307 Add hakiri security badge to README
  README.md
Labels: housekeeping

#311 Refresh VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec/GET-confirm_edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec/GET-edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec/GET-edit_complete_form.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec/when-WasteExemptionsEngine-configuration-edit_enabled-is-true-.yml
  spec/cassettes/w3c_valid_content/errors_spec/-show.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/location_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec/GET-renew_with_changes_form.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec/GET-renew_without_changes_form.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/start_forms_spec/GET-start_form.yml
Labels: housekeeping

#312 Add `already_renewed?` method to Registration
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/waste_exemptions_engine/registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: enhancement

#310 Redirect to start form page when a token is invalid
  app/controllers/waste_exemptions_engine/forms_controller.rb
Labels: bug

#313 Add `#renewal?` method to registration objects
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  spec/models/waste_exemptions_engine/edit_registration_spec.rb
  spec/models/waste_exemptions_engine/new_registration_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_spec.rb
Labels: enhancement

#314 Forms refactoring - Move validations to the top
  app/forms/waste_exemptions_engine/address_lookup_form.rb
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/applicant_name_form.rb
  app/forms/waste_exemptions_engine/applicant_phone_form.rb
  app/forms/waste_exemptions_engine/base_form.rb
  app/forms/waste_exemptions_engine/business_type_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_email_form.rb
  app/forms/waste_exemptions_engine/contact_name_form.rb
  app/forms/waste_exemptions_engine/contact_phone_form.rb
  app/forms/waste_exemptions_engine/contact_position_form.rb
  app/forms/waste_exemptions_engine/declaration_form.rb
  app/forms/waste_exemptions_engine/exemptions_form.rb
  app/forms/waste_exemptions_engine/is_a_farmer_form.rb
  app/forms/waste_exemptions_engine/location_form.rb
  app/forms/waste_exemptions_engine/main_people_form.rb
  app/forms/waste_exemptions_engine/on_a_farm_form.rb
  app/forms/waste_exemptions_engine/operator_address_form.rb
  app/forms/waste_exemptions_engine/operator_address_lookup_form.rb
  app/forms/waste_exemptions_engine/operator_address_manual_form.rb
  app/forms/waste_exemptions_engine/operator_name_form.rb
  app/forms/waste_exemptions_engine/operator_postcode_form.rb
  app/forms/waste_exemptions_engine/person_form.rb
  app/forms/waste_exemptions_engine/postcode_form.rb
  app/forms/waste_exemptions_engine/register_in_northern_ireland_form.rb
  app/forms/waste_exemptions_engine/register_in_scotland_form.rb
  app/forms/waste_exemptions_engine/register_in_wales_form.rb
  app/forms/waste_exemptions_engine/registration_complete_form.rb
  app/forms/waste_exemptions_engine/registration_number_form.rb
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  app/forms/waste_exemptions_engine/start_form.rb
Labels: housekeeping

#315 Use applicant first and last name transient registration params
  app/forms/waste_exemptions_engine/applicant_name_form.rb
  app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
  config/locales/forms/applicant_name_forms/en.yml
  spec/forms/waste_exemptions_engine/applicant_name_form_spec.rb
  spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
Labels: housekeeping

#320 Rename translation errors parameters
  config/locales/forms/applicant_name_forms/en.yml
Labels: housekeeping

#321 Form refactoring - Rename contact first and last names
  app/forms/waste_exemptions_engine/contact_name_form.rb
  app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
  config/locales/forms/contact_name_forms/en.yml
  spec/forms/waste_exemptions_engine/contact_name_form_spec.rb
  spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb
Labels: housekeeping

#318 Make confirmed email an attribute of the form
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  spec/support/shared_examples/requests/post_form.rb
Labels: housekeeping

#319 Forms refactoring - applicant phone number
  app/forms/waste_exemptions_engine/applicant_phone_form.rb
  app/views/waste_exemptions_engine/applicant_phone_forms/new.html.erb
  config/locales/forms/applicant_phone_forms/en.yml
  spec/forms/waste_exemptions_engine/applicant_phone_form_spec.rb
  spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
Labels: housekeeping

#324 Forms refactoring - Use helpers to format names
  app/forms/waste_exemptions_engine/data_overview_form.rb
  app/forms/waste_exemptions_engine/edit_form.rb
  app/helpers/waste_exemptions_engine/application_helper.rb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_applicant.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_contact.html.erb
  spec/dummy/app/helpers/application_helper.rb
  spec/helpers/waste_exemptions_engine/application_helper_spec.rb
Labels: housekeeping

#325 Forms refactoring - Exemptions form division of responsibilities
  app/forms/waste_exemptions_engine/exemptions_form.rb
  app/helpers/waste_exemptions_engine/exemptions_forms_helper.rb
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  config/locales/forms/exemptions_forms/en.yml
  spec/forms/waste_exemptions_engine/exemptions_form_spec.rb
  spec/helpers/waste_exemptions_engine/exemptions_forms_helper_spec.rb
  spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb
Labels: housekeeping

#326 Forms refactoring - Main People Form
  app/forms/waste_exemptions_engine/main_people_form.rb
  app/forms/waste_exemptions_engine/person_form.rb
  app/models/concerns/waste_exemptions_engine/can_limit_number_of_main_people.rb
  app/models/waste_exemptions_engine/person.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  app/validators/waste_exemptions_engine/main_person_validator.rb
  app/validators/waste_exemptions_engine/person_validator.rb
  app/views/waste_exemptions_engine/main_people_forms/new.html.erb
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/forms/waste_exemptions_engine/main_people_form_spec.rb
  spec/requests/waste_exemptions_engine/main_people_forms_spec.rb
  spec/services/waste_exemptions_engine/confirmation_pdf_generator_service_spec.rb
  spec/support/shared_examples/requests/post_form.rb
  spec/validators/waste_exemptions_engine/main_person_validator_spec.rb
  spec/validators/waste_exemptions_engine/person_validator_spec.rb
Labels: housekeeping

#329 Prevent random failure of scenario
  spec/helpers/waste_exemptions_engine/exemptions_forms_helper_spec.rb
Labels: housekeeping

#328 Rename start to start_option in the StartForm
  app/forms/waste_exemptions_engine/start_form.rb
  app/views/waste_exemptions_engine/start_forms/new.html.erb
  config/locales/forms/start_forms/en.yml
  spec/forms/waste_exemptions_engine/start_form_spec.rb
  spec/requests/waste_exemptions_engine/start_forms_spec.rb
Labels: housekeeping

#327 Move view logic away from forms - Renewal and Registration complete
  app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
  app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
  app/forms/waste_exemptions_engine/registration_complete_form.rb
  app/forms/waste_exemptions_engine/renewal_complete_form.rb
  app/helpers/waste_exemptions_engine/plurals_helper.rb
  app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
  app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
  spec/helpers/waste_exemptions_engine/plurals_helper_spec.rb
Labels: housekeeping
