Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-04, with the labels that each got.

#113 Refactor boolean config values to behave as booleans
  config/initializers/wickedpdf.rb
  lib/waste_exemptions_engine.rb
Labels: housekeeping

#112 Add email interception and retrieval
  app/controllers/waste_exemptions_engine/last_email_controller.rb
  app/services/waste_exemptions_engine/last_email_cache_service.rb
  config/routes.rb
  lib/waste_exemptions_engine.rb
  spec/dummy/.env.example
  spec/dummy/config/initializers/waste_exemptions_engine.rb
  spec/requests/waste_exemptions_engine/last_email_spec.rb
  spec/services/waste_exemptions_engine/last_email_cache_service_spec.rb
Labels: enhancement

#115 Format dates with unpadded day instead of blank-padded
  config/initializers/time_formats.rb
Labels: bug

#116 Fix typo
  config/locales/forms/contact_agency_forms/en.yml
Labels: bug

#118 Add missing tests for GeneratePdfService
  spec/services/waste_exemptions_engine/generate_pdf_service_spec.rb
Labels: housekeeping

#119 Add html view which is used to generate PDF privacy
  app/views/waste_exemptions_engine/pdfs/privacy_policy.html
Labels: enhancement

#122 Add Bullet as a dependency and integrate into RSpec
  Gemfile.lock
  spec/cassettes/company_no_valid.yml
  spec/dummy/config/environments/test.rb
  spec/rails_helper.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#125 Update VCR cassettes
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: housekeeping

#121 Attach privacy policy pdf to confirmation
  app/mailers/waste_exemptions_engine/confirmation_mailer.rb
  lib/privacy_policy.pdf
  spec/cassettes/company_no_valid.yml
  spec/factories/registration.rb
  spec/mailers/waste_exemptions_engine/confirmation_mailer_spec.rb
Labels: enhancement

#133 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: housekeeping

#135 Refactor address workflow tests to use shared examples
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_postcode_form_spec.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_postcode_transition.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/an_address_lookup_transition.rb
Labels: housekeeping

#141 Raise completition errors to the customer
  app/services/waste_exemptions_engine/registration_completion_service.rb
  spec/requests/waste_exemptions_engine/registration_complete_forms_spec.rb
Labels: bug

#145 Fix error routes to contain a constraint for the /error path
  config/routes.rb
Labels: bug

#136 Remove byebug and swap it with pry-byebug
  Gemfile.lock
  spec/spec_helper.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#144 Change "can't" to "cannot" in privacy policy PDF
  app/views/waste_exemptions_engine/pdfs/privacy_policy.html
  lib/privacy_policy.pdf
Labels: enhancement

#139 Implement editing
  app/controllers/waste_exemptions_engine/edit_complete_forms_controller.rb
  app/controllers/waste_exemptions_engine/edit_forms_controller.rb
  app/forms/waste_exemptions_engine/edit_complete_form.rb
  app/forms/waste_exemptions_engine/edit_form.rb
  app/helpers/waste_exemptions_engine/edit_helper.rb
  app/models/concerns/waste_exemptions_engine/can_use_edit_registration_workflow.rb
  app/models/waste_exemptions_engine/edit_registration.rb
  app/services/waste_exemptions_engine/edit_completion_service.rb
  app/views/waste_exemptions_engine/edit_complete_forms/new.html.erb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  config/locales/forms/edit_complete_forms/en.yml
  config/locales/forms/edit_forms/en.yml
  config/routes.rb
  spec/factories/address.rb
  spec/factories/edit_registration.rb
  spec/factories/forms/edit_complete_form.rb
  spec/factories/forms/edit_form.rb
  spec/factories/person.rb
  spec/factories/registration.rb
  spec/forms/waste_exemptions_engine/edit_complete_form_spec.rb
  spec/helpers/waste_exemptions_engine/edit_helper_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/applicant_email_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/applicant_name_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/applicant_phone_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_email_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_name_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_phone_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_position_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/contact_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/declaration_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/edit_complete_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/edit_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/is_a_farmer_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/location_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/main_people_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/on_a_farm_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/operator_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/operator_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/operator_name_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/operator_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_northern_ireland_form.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_scotland_form.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_wales_form.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/registration_number_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/site_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/site_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/site_grid_reference_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/site_postcode_form_spec.rb
  spec/requests/waste_exemptions_engine/edit_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_forms_spec.rb
  spec/services/waste_exemptions_engine/edit_completion_service_spec.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_simple_monodirectional_transition.rb
Labels: enhancement

#143 Display metadata about EditRegistration
  app/helpers/waste_exemptions_engine/edit_helper.rb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  config/initializers/time_formats.rb
  config/locales/forms/edit_forms/en.yml
  spec/helpers/waste_exemptions_engine/edit_helper_spec.rb
Labels: enhancement

#146 Remove expectations for private methods from location specs
  spec/models/waste_exemptions_engine/new_registration_workflow_state/location_form_spec.rb
Labels: housekeeping
