Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-05, with the labels that each got.

#151 Fix up styling on edit page
  app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
Labels: enhancement

#154 Don't skip last email request tests
  spec/requests/waste_exemptions_engine/last_email_spec.rb
Labels: housekeeping

#152 Don't modify status of unedited exemptions
  app/services/waste_exemptions_engine/edit_completion_service.rb
  spec/services/waste_exemptions_engine/edit_completion_service_spec.rb
Labels: bug

#155 Refactoring of PDF matchers spec helper to use an include strategy
  spec/fixtures/pdfs/confirmation.pdf
  spec/services/waste_exemptions_engine/confirmation_pdf_generator_service_spec.rb
  spec/support/pdf_matchers.rb
Labels: housekeeping

#153 Fixes error handling redirect to internale error app
  app/controllers/waste_exemptions_engine/errors_controller.rb
  config/initializers/error_pages.rb
  config/routes.rb
  spec/dummy/config/environments/test.rb
  spec/dummy/config/routes.rb
  spec/requests/waste_exemptions_engine/errors_spec.rb
  spec/support/error_response_helper.rb
Labels: bug

#147 Add a feature switch and permissions check for editing
  app/controllers/concerns/waste_exemptions_engine/permission_checks.rb
  app/controllers/waste_exemptions_engine/application_controller.rb
  app/controllers/waste_exemptions_engine/edit_forms_controller.rb
  app/controllers/waste_exemptions_engine/forms_controller.rb
  lib/waste_exemptions_engine.rb
  spec/requests/waste_exemptions_engine/confirm_edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_forms_spec.rb
Labels: enhancement

#157 Refactoring of factories to use the Faker gem
  Gemfile.lock
  spec/factories/address.rb
  spec/factories/exemption.rb
  spec/factories/new_registration.rb
  spec/factories/person.rb
  spec/factories/registration.rb
  spec/factories/transient_address.rb
  spec/factories/transient_person.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
  spec/support/faker.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#161 Fix bug on confirmation PDF generation for lookup addresses
  app/models/waste_exemptions_engine/address.rb
  app/views/waste_exemptions_engine/pdfs/_site_address_grid_reference.html.erb
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
  config/locales/pdfs/certificate.en.yml
  spec/factories/address.rb
  spec/factories/registration.rb
  spec/models/waste_exemptions_engine/address_spec.rb
  spec/services/waste_exemptions_engine/confirmation_pdf_generator_service_spec.rb
Labels: bug

#159 Fix error on data address lookup error handling
  app/models/waste_exemptions_engine/transient_address.rb
  spec/models/waste_exemptions_engine/transient_address_spec.rb
Labels: bug

#163 Fix permission checking for edit functionality
  app/controllers/concerns/waste_exemptions_engine/edit_permission_checks.rb
  app/controllers/concerns/waste_exemptions_engine/permission_checks.rb
  app/controllers/waste_exemptions_engine/application_controller.rb
  app/controllers/waste_exemptions_engine/edit_cancelled_forms_controller.rb
  app/controllers/waste_exemptions_engine/edit_complete_forms_controller.rb
  app/controllers/waste_exemptions_engine/edit_forms_controller.rb
  app/controllers/waste_exemptions_engine/forms_controller.rb
  spec/requests/waste_exemptions_engine/edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/edit_forms_spec.rb
Labels: bug

#164 Make declaration form not flexibly navigable
  app/forms/waste_exemptions_engine/declaration_form.rb
  spec/forms/waste_exemptions_engine/declaration_form_spec.rb
Labels: bug

#165 Fix path to manual address in the site address page
  app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
Labels: bug

#167 Move edit authorization checking to its own service
  app/controllers/concerns/waste_exemptions_engine/edit_permission_checks.rb
  app/services/waste_exemptions_engine/edit_permission_checker_service.rb
Labels: bug

#168 Put GOV.UK style inline for confirmation PDF
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
Labels: bug

#156 Make the completition form not flexibly navigatable
  app/forms/waste_exemptions_engine/registration_complete_form.rb
  spec/forms/waste_exemptions_engine/registration_complete_form_spec.rb
  spec/requests/waste_exemptions_engine/registration_complete_forms_spec.rb
Labels: bug

#170 Set table name before including state machine concern
  app/models/waste_exemptions_engine/transient_registration_exemption.rb
  spec/support/shared_examples/models/activator_of_exemptions.rb
Labels: bug

#171 Copy over to transient Edit registration only active exemptions
  app/models/waste_exemptions_engine/edit_registration.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  spec/factories/registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: bug

#173 Add cannot edit to the exemptions section in edit screen
  app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
Labels: enhancement

#174 Change headings and table layout on edit site location
  app/models/concerns/waste_exemptions_engine/can_be_located_by_grid_reference.rb
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/transient_address.rb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  config/locales/forms/edit_forms/en.yml
Labels: enhancement

#175 Fix conditionals on main people page
  app/views/waste_exemptions_engine/main_people_forms/new.html.erb
Labels: bug

#172 Remove ability to edit location
  app/controllers/waste_exemptions_engine/edit_forms_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_edit_registration_workflow.rb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  config/routes.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/edit_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/location_form_spec.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_northern_ireland_form.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_scotland_form.rb
  spec/models/waste_exemptions_engine/edit_registration_workflow_state/register_in_wales_form.rb
  spec/requests/waste_exemptions_engine/edit_forms_spec.rb
Labels: enhancement

#179 Align edit table info to the top vertically
  app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
Labels: enhancement

#176 Remove wicked_pdf stlesheet helper
  app/helpers/waste_exemptions_engine/application_helper.rb
Labels: housekeeping

#180 Remove duplicate partnership? method
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  spec/presenters/waste_exemptions_engine/certificate_presenter_spec.rb
Labels: housekeeping

#178 Use headings inside table caption for design consistency
  app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
Labels: enhancement

#181 Move up reference link to manual address for site form
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
  config/locales/forms/site_grid_reference_forms/en.yml
Labels: enhancement

#177 Remove copy over of exemptions informations from registration to transient registration for editing
  app/models/waste_exemptions_engine/edit_registration.rb
  app/services/waste_exemptions_engine/edit_completion_service.rb
  spec/factories/edit_registration.rb
  spec/services/waste_exemptions_engine/edit_completion_service_spec.rb
Labels: bug

#184 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: housekeeping

#182 Use `consider_all_requests_local` as a conditional to the exeptions a…
  config/initializers/error_pages.rb
Labels: housekeeping

#185 Fix capital letter on translation
  config/locales/forms/edit_forms/en.yml
Labels: bug

#189 Fix `cannot edit` label in caption to float right inline with title
  app/assets/stylesheets/waste_exemptions_engine/partials/_edit.scss
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
Labels: bug

#190 Rename deregistered_on to deregistered_at
  db/migrate/20190522085202_rename_deregistered_on_to_deregistered_at.rb
  spec/dummy/db/schema.rb
  spec/support/helpers/model_properties.rb
Labels: housekeeping

#192 Update to work with validators namespace change
  Gemfile.lock
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/registration_number_form.rb
  lib/waste_exemptions_engine.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/registration_number_form_spec.rb
Labels: housekeeping

#193 Require wicked pdf at a Rails level
  app/services/waste_exemptions_engine/confirmation_pdf_generator_service.rb
  app/services/waste_exemptions_engine/generate_pdf_service.rb
  lib/waste_exemptions_engine/engine.rb
  spec/mailers/waste_exemptions_engine/confirmation_mailer_spec.rb
  spec/services/waste_exemptions_engine/generate_pdf_service_spec.rb
Labels: bug

#188 Do not save un-persisted objects in workflow setup
  app/controllers/waste_exemptions_engine/forms_controller.rb
  app/forms/waste_exemptions_engine/edit_form.rb
Labels: bug

#196 Remove second link to manual address
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
Labels: enhancement
