Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-09, with the labels that each got.

#335 Postcode form - Postcode validator
  app/forms/waste_exemptions_engine/postcode_form.rb
  app/validators/waste_exemptions_engine/postcode_validator.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/site_grid_reference_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/site_grid_reference_form_spec.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_postcode_transition.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/an_address_lookup_transition.rb
Labels: housekeeping

#337 Fix error on Airbrake report
  app/services/waste_exemptions_engine/address_finder_service.rb
Labels: bug

#330 Address form - Remove AddressForm and create an AddressHelper
  app/forms/concerns/waste_exemptions_engine/can_add_or_replace_an_address.rb
  app/forms/waste_exemptions_engine/address_form.rb
  app/forms/waste_exemptions_engine/address_lookup_form.rb
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  lib/waste_exemptions_engine/engine.rb
  spec/forms/concerns/waste_exemptions_engine/can_add_or_replace_an_address_spec.rb
  spec/support/shared_examples/forms/address_lookup_form.rb
  spec/support/shared_examples/forms/address_manual_form.rb
Labels: housekeeping

#332 Operator postcode form refactoring
  app/forms/waste_exemptions_engine/base_postcode_form.rb
  app/forms/waste_exemptions_engine/operator_postcode_form.rb
  app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
  config/locales/forms/operator_postcode_forms/en.yml
  spec/forms/waste_exemptions_engine/operator_postcode_form_spec.rb
  spec/requests/waste_exemptions_engine/operator_postcode_forms_spec.rb
Labels: housekeeping

#336 Site postcode form refactoring
  app/forms/waste_exemptions_engine/site_postcode_form.rb
  app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
  config/locales/forms/site_postcode_forms/en.yml
  spec/forms/waste_exemptions_engine/site_postcode_form_spec.rb
  spec/requests/waste_exemptions_engine/site_postcode_forms_spec.rb
Labels: housekeeping

#333 Contact postcode form refactoring
  app/forms/waste_exemptions_engine/contact_postcode_form.rb
  app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
  config/locales/forms/contact_postcode_forms/en.yml
  spec/forms/waste_exemptions_engine/contact_postcode_form_spec.rb
  spec/requests/waste_exemptions_engine/contact_postcode_forms_spec.rb
Labels: housekeeping

#340 Add transient addresses has_one associations to TransientRegistration
  app/models/waste_exemptions_engine/transient_registration.rb
  spec/factories/edit_registration.rb
  spec/factories/new_registration.rb
  spec/factories/renewing_registration.rb
  spec/support/shared_examples/models/transient_registration.rb
Labels: housekeeping

#343 Use rails associations to define associations with the addresses
  app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  spec/factories/edit_registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/support/shared_examples/models/owner_of_registration_attributes.rb
  spec/support/shared_examples/models/transient_registration.rb
Labels: housekeeping

#344 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec/GET-confirm_edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec/GET-edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec/GET-edit_complete_form.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec/when-WasteExemptionsEngine-configuration-edit_enabled-is-true-.yml
  spec/cassettes/w3c_valid_content/errors_spec/-show.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/location_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec/GET-renew_with_changes_form.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec/GET-renew_without_changes_form.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/start_forms_spec/GET-start_form.yml
Labels: housekeeping

#346 Update schema following RUBY-580
  spec/dummy/db/schema.rb
Labels: enhancement

#348 Update exemptions style
  app/assets/stylesheets/waste_exemptions_engine/application.scss
  app/assets/stylesheets/waste_exemptions_engine/partials/_exemptions.scss
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  config/locales/forms/exemptions_forms/en.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
Labels: enhancement

#353 Remove exemptions checkbox from inside label
  app/assets/stylesheets/waste_exemptions_engine/application.scss
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
Labels: enhancement

#355 Add active_and_expired_exemptions scope to registrations
  app/models/waste_exemptions_engine/registration.rb
  spec/factories/registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: enhancement

#356 Add visually hidden name info to delete partner button
  app/views/waste_exemptions_engine/main_people_forms/new.html.erb
Labels: enhancement

#347 Identify EA Administrative Area for new regs.
  Gemfile.lock
  app/models/waste_exemptions_engine/transient_address.rb
  app/services/waste_exemptions_engine/area_lookup_service.rb
  lib/waste_exemptions_engine/engine.rb
  spec/cassettes/site_address_auto_x_and_y_and_area.yml
  spec/cassettes/site_address_from_grid_ref_auto_area.yml
  spec/cassettes/site_address_from_lookup_auto_area.yml
  spec/models/waste_exemptions_engine/transient_address_spec.rb
  spec/services/waste_exemptions_engine/area_lookup_service_spec.rb
  waste_exemptions_engine.gemspec
Labels: enhancement

#357 Fix broken link to NRW waste exemptions page
  app/views/waste_exemptions_engine/register_in_wales_forms/new.html.erb
Labels: bug

#361 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: housekeeping

#358 Add scopes to the address models for area lookup
  app/models/waste_exemptions_engine/address.rb
  spec/models/waste_exemptions_engine/address_spec.rb
Labels: enhancement

#363 Clean db from Addresses
  spec/models/waste_exemptions_engine/address_spec.rb
Labels: bug

#365 Restrict address missing scopes to site addresses
  app/models/waste_exemptions_engine/address.rb
  spec/models/waste_exemptions_engine/address_spec.rb
Labels: bug

#366 Revert "Restrict address missing scopes to site addresses (#365)"
  app/models/waste_exemptions_engine/address.rb
  spec/models/waste_exemptions_engine/address_spec.rb
Labels: housekeeping

#364 Do not run area lookups on 0 coordinates
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/transient_address.rb
  app/services/waste_exemptions_engine/area_lookup_service.rb
  spec/models/waste_exemptions_engine/address_spec.rb
Labels: enhancement

#368 Site Address manual form refactoring
  app/forms/waste_exemptions_engine/site_address_manual_form.rb
  app/views/waste_exemptions_engine/site_address_manual_forms/new.html.erb
  spec/forms/waste_exemptions_engine/site_address_manual_form_spec.rb
  spec/requests/waste_exemptions_engine/site_address_manual_forms_spec.rb
Labels: housekeeping

#367 Operator Address manual form refactoring
  app/forms/waste_exemptions_engine/operator_address_manual_form.rb
  app/views/waste_exemptions_engine/operator_address_manual_forms/new.html.erb
  spec/forms/waste_exemptions_engine/operator_address_manual_form_spec.rb
  spec/requests/waste_exemptions_engine/operator_address_manual_forms_spec.rb
Labels: housekeeping

#369 Cleanup classes after manual forms refactoring
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/validators/waste_exemptions_engine/legacy_manual_address_validator.rb
  spec/support/shared_examples/forms/a_manual_address_form.rb
  spec/validators/waste_exemptions_engine/legacy_manual_address_validator_spec.rb
Labels: housekeeping

#371 Remove file that got in there by mistake
  app/forms/waste_exemptions_engine/Find Results
Labels: housekeeping

#372 Remove unused class
  app/forms/waste_exemptions_engine/postcode_form.rb
Labels: housekeeping

#373 Remove addresses forms shared classes
  app/forms/waste_exemptions_engine/contact_address_form.rb
  app/forms/waste_exemptions_engine/contact_address_lookup_form.rb
  app/forms/waste_exemptions_engine/operator_address_form.rb
  app/forms/waste_exemptions_engine/operator_address_lookup_form.rb
  app/forms/waste_exemptions_engine/site_address_form.rb
  app/forms/waste_exemptions_engine/site_address_lookup_form.rb
  spec/forms/waste_exemptions_engine/contact_address_lookup_form_spec.rb
  spec/forms/waste_exemptions_engine/operator_address_lookup_form_spec.rb
  spec/forms/waste_exemptions_engine/site_address_lookup_form_spec.rb
Labels: housekeeping

#375 Refactor address lookups form
  app/forms/concerns/waste_exemptions_engine/can_create_address_from_finder_data.rb
  app/forms/waste_exemptions_engine/address_lookup_form_base.rb
  app/forms/waste_exemptions_engine/contact_address_lookup_form.rb
  app/forms/waste_exemptions_engine/operator_address_lookup_form.rb
  app/forms/waste_exemptions_engine/site_address_lookup_form.rb
  spec/support/shared_examples/forms/address_lookup_form.rb
Labels: housekeeping

#377 Contact Position Form refactoring
  app/forms/waste_exemptions_engine/contact_position_form.rb
  app/views/waste_exemptions_engine/contact_position_forms/new.html.erb
  spec/forms/waste_exemptions_engine/contact_position_form_spec.rb
  spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb
Labels: housekeeping

#376 Site Grid Reference Form Refactoring
  app/forms/concerns/waste_exemptions_engine/can_add_or_replace_an_address.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  spec/forms/concerns/waste_exemptions_engine/can_add_or_replace_an_address_spec.rb
Labels: housekeeping
