Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-06, with the labels that each got.

#201 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
Labels: housekeeping

#202 Raise I18n errors during tests
  spec/dummy/config/environments/test.rb
Labels: housekeeping

#203 Allow a service main method to receive no params
  app/services/waste_exemptions_engine/base_service.rb
Labels: enhancement

#204 Add area attribute to addresses
  db/migrate/20190603152123_add_area_to_addresses.rb
  db/migrate/20190603215354_add_area_to_transient_addresses.rb
  spec/dummy/db/schema.rb
  spec/support/helpers/model_properties.rb
Labels: enhancement

#198 Create a hash for business types
  app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_exemptions_engine/can_limit_number_of_main_people.rb
  app/validators/waste_exemptions_engine/business_type_validator.rb
  app/views/waste_exemptions_engine/business_type_forms/new.html.erb
  spec/factories/new_registration.rb
  spec/factories/registration.rb
  spec/forms/waste_exemptions_engine/business_type_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/business_type_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/operator_name_form_spec.rb
  spec/support/shared_examples/models/owner_of_registration_attributes.rb
  spec/validators/waste_exemptions_engine/business_type_validator_spec.rb
Labels: housekeeping

#208 Switch to using TrueFalse validator in gem
  app/forms/waste_exemptions_engine/is_a_farmer_form.rb
  app/forms/waste_exemptions_engine/on_a_farm_form.rb
  app/validators/waste_exemptions_engine/yes_no_validator.rb
  spec/forms/waste_exemptions_engine/is_a_farmer_form_spec.rb
  spec/forms/waste_exemptions_engine/on_a_farm_form_spec.rb
  spec/validators/waste_exemptions_engine/yes_no_validator_spec.rb
Labels: housekeeping

#211 Update address lookup test, reload cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/support/shared_examples/forms/address_lookup_form.rb
Labels: housekeeping

#214 Auto-determine grid reference for site address
  app/models/waste_exemptions_engine/transient_address.rb
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/models/waste_exemptions_engine/transient_address_spec.rb
Labels: enhancement

#212 Add HTML w3c test coverage
  Gemfile.lock
  app/services/waste_exemptions_engine/address_finder_service.rb
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec.yml
  spec/cassettes/w3c_valid_content/location_forms_spec.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec.yml
  spec/factories/forms/operator_name_form.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb
  spec/support/helpers/html_body_content_matcher.rb
  spec/support/html_matchers.rb
  spec/support/shared_examples/requests/get_form.rb
  spec/support/vcr.rb
  waste_exemptions_engine.gemspec
Labels: bug, enhancement

#218 Add versions archive table migration
  db/migrate/20190625221942_create_version_archives.rb
  spec/dummy/db/schema.rb
Labels: housekeeping
