Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-07, with the labels that each got.

#220 Store a single version of registration and its relations
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/waste_exemptions_engine/edit_completion_service.rb
  db/migrate/20190626142528_add_json_to_versions.rb
  spec/dummy/db/schema.rb
  spec/factories/edit_registration.rb
  spec/models/waste_exemptions_engine/address_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/services/waste_exemptions_engine/edit_completion_service_spec.rb
  spec/support/shared_examples/models/has_paper_trail.rb
Labels: enhancement

#221 Refresh VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec.yml
  spec/cassettes/w3c_valid_content/location_forms_spec.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec.yml
Labels: housekeeping

#222 Add feature toggles class to reuse in apps
  app/models/waste_exemptions_engine/feature_toggle.rb
  spec/dummy/config/feature_toggles.yml
  spec/models/waste_exemptions_engine/feature_toggle_spec.rb
Labels: enhancement

#199 Tidy up views
  app/views/layouts/waste_exemptions_engine/application.html.erb
  app/views/pages/os-terms.html.erb
  app/views/pages/version.html.erb
  app/views/waste_exemptions_engine/applicant_email_forms/new.html.erb
  app/views/waste_exemptions_engine/applicant_name_forms/new.html.erb
  app/views/waste_exemptions_engine/applicant_phone_forms/new.html.erb
  app/views/waste_exemptions_engine/business_type_forms/new.html.erb
  app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb
  app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
  app/views/waste_exemptions_engine/contact_address_manual_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_email_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_name_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_phone_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_position_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_postcode_forms/new.html.erb
  app/views/waste_exemptions_engine/edit_forms/new.html.erb
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  app/views/waste_exemptions_engine/is_a_farmer_forms/new.html.erb
  app/views/waste_exemptions_engine/location_forms/new.html.erb
  app/views/waste_exemptions_engine/on_a_farm_forms/new.html.erb
  app/views/waste_exemptions_engine/operator_address_manual_forms/new.html.erb
  app/views/waste_exemptions_engine/operator_name_forms/new.html.erb
  app/views/waste_exemptions_engine/operator_postcode_forms/new.html.erb
  app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
  app/views/waste_exemptions_engine/registration_number_forms/new.html.erb
  app/views/waste_exemptions_engine/shared/_manual_address.html.erb
  app/views/waste_exemptions_engine/shared/_person_name.html.erb
  app/views/waste_exemptions_engine/shared/_select_address.html.erb
  app/views/waste_exemptions_engine/site_address_manual_forms/new.html.erb
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
  app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
  app/views/waste_exemptions_engine/start_forms/new.html.erb
Labels: housekeeping

#228 User correct variable name for error
  app/services/waste_exemptions_engine/registration_completion_service.rb
Labels: bug

#225 Show error messages in line with address select fields
  app/views/waste_exemptions_engine/shared/_select_address.html.erb
Labels: bug

#226 Test coverage for error messages
  app/views/waste_exemptions_engine/shared/_errors.html.erb
  spec/requests/waste_exemptions_engine/applicant_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/business_type_forms_spec.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_exemptions_engine/confirm_edit_cancelled_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_address_lookup_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_address_manual_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_position_forms_spec.rb
  spec/requests/waste_exemptions_engine/contact_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/declaration_forms_spec.rb
  spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb
  spec/requests/waste_exemptions_engine/is_a_farmer_forms_spec.rb
  spec/requests/waste_exemptions_engine/location_forms_spec.rb
  spec/requests/waste_exemptions_engine/main_people_forms_spec.rb
  spec/requests/waste_exemptions_engine/on_a_farm_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_address_lookup_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_address_manual_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_postcode_forms_spec.rb
  spec/requests/waste_exemptions_engine/registration_number_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_address_lookup_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_address_manual_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_grid_reference_forms_spec.rb
  spec/requests/waste_exemptions_engine/site_postcode_forms_spec.rb
  spec/support/shared_examples/requests/post_form.rb
Labels: housekeeping

#229 Show second error message on declaration page
  app/views/waste_exemptions_engine/declaration_forms/new.html.erb
  spec/requests/waste_exemptions_engine/declaration_forms_spec.rb
Labels: enhancement

#230 Update date on privacy policy PDF
  app/views/waste_exemptions_engine/pdfs/privacy_policy.html
Labels: housekeeping

#232 Update date in privacy policy PDF
  lib/privacy_policy.pdf
Labels: bug

#233 Create reference using the registration id
  app/models/waste_exemptions_engine/new_registration.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
Labels: enhancement

#234 Fixes registration number appearing after the declaration page
  app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
Labels: bug

#235 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec.yml
  spec/cassettes/w3c_valid_content/location_forms_spec.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec.yml
Labels: housekeeping

#240 Fix Travis
  .travis.yml
Labels: bug

#237 Use DB Pessimistic locking to prevent race conditions
  app/services/waste_exemptions_engine/registration_completion_service.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
Labels: bug

#236 Create a new transient registration for WEX renewals
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  app/services/waste_exemptions_engine/renewal_start_service.rb
  app/views/waste_exemptions_engine/renews/new.html.erb
  config/routes.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/renewing_registration_spec.rb
  spec/requests/waste_exemptions_engine/renew_spec.rb
  spec/requests/waste_exemptions_engine/start_forms_spec.rb
  spec/services/waste_exemptions_engine/renewal_start_service_spec.rb
Labels: enhancement

#241 Create new state machine for renewals
  app/controllers/waste_exemptions_engine/renew_with_changes_forms_controller.rb
  app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
  app/controllers/waste_exemptions_engine/renewal_start_forms_controller.rb
  app/forms/waste_exemptions_engine/renew_with_changes_form.rb
  app/forms/waste_exemptions_engine/renewal_complete_form.rb
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  app/models/waste_exemptions_engine/renewing_registration.rb
  app/views/waste_exemptions_engine/renew_with_changes_forms/new.html.erb
  app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
  app/views/waste_exemptions_engine/renewal_start_forms/new.html.erb
  app/views/waste_exemptions_engine/renews/new.html.erb
  config/locales/forms/renew_with_changes_forms/en.yml
  config/locales/forms/renewal_complete_forms/en.yml
  config/locales/forms/renewal_start_forms/en.yml
  config/routes.rb
  spec/factories/forms/renewal_complete_form.rb
  spec/factories/forms/renewal_start_form.rb
  spec/factories/forms/renewal_with_changes_form.rb
  spec/forms/waste_exemptions_engine/renewal_complete_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renew_with_changes_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_complete_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_start_form_spec.rb
  spec/requests/waste_exemptions_engine/renew_with_changes_forms_spec.rb
  spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
  spec/requests/waste_exemptions_engine/renewal_start_forms_spec.rb
Labels: enhancement

#239 Change position of the Exemptions form
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/applicant_name_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/check_your_answers_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/exemptions_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/location_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/site_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/site_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/site_grid_reference_form_spec.rb
  spec/support/helpers/workflow_states.rb
  spec/support/shared_examples/requests/get_form.rb
  spec/support/shared_examples/requests/post_form.rb
Labels: enhancement

#244 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_auto_x_and_y.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec.yml
  spec/cassettes/w3c_valid_content/location_forms_spec.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec.yml
Labels: housekeeping

#247 Complete renewal and create new registration
  app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
  app/controllers/waste_exemptions_engine/renewal_complete_forms_controller.rb
  app/forms/waste_exemptions_engine/renewal_complete_form.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
  app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
  config/locales/forms/renewal_complete_forms/en.yml
  spec/requests/waste_exemptions_engine/renewal_complete_forms_spec.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
Labels: enhancement
