Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-01, with the labels that each got.

#21 Add check your answers page
  app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/helpers/waste_exemptions_engine/application_helper.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/validators/waste_exemptions_engine/address_validator.rb
  app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb
  config/locales/forms/check_your_answers_forms/en.yml
  config/routes.rb
Labels: enhancement

#22 Add site postcode page
  .travis.yml
  app/controllers/waste_exemptions_engine/site_grid_reference_forms_controller.rb
  app/controllers/waste_exemptions_engine/site_postcode_forms_controller.rb
  app/forms/waste_exemptions_engine/site_postcode_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/views/waste_exemptions_engine/site_grid_reference_forms/new.html.erb
  app/views/waste_exemptions_engine/site_postcode_forms/new.html.erb
  config/locales/forms/site_postcode_forms/en.yml
  config/routes.rb
  db/migrate/20190103103408_add_site_postcode_to_interims.rb
Labels: enhancement

#23 Update string handling to match WCR
  app/forms/waste_exemptions_engine/address_manual_form.rb
  app/forms/waste_exemptions_engine/postcode_form.rb
  app/models/concerns/waste_exemptions_engine/can_strip_whitespace.rb
Labels: housekeeping

#24 Add site address lookup page
  app/controllers/waste_exemptions_engine/site_address_lookup_forms_controller.rb
  app/forms/waste_exemptions_engine/site_address_form.rb
  app/forms/waste_exemptions_engine/site_address_lookup_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/views/waste_exemptions_engine/site_address_lookup_forms/new.html.erb
  config/locales/forms/site_address_lookup_forms/en.yml
  config/routes.rb
Labels: enhancement

#25 Add site manual address entry page
  app/controllers/waste_exemptions_engine/site_address_manual_forms_controller.rb
  app/forms/waste_exemptions_engine/site_address_manual_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/models/waste_exemptions_engine/address.rb
  app/views/waste_exemptions_engine/site_address_manual_forms/new.html.erb
  config/locales/forms/site_address_manual_forms/en.yml
  config/routes.rb
Labels: enhancement

#26 Add declaration page
  app/controllers/waste_exemptions_engine/declaration_forms_controller.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/declaration_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/views/waste_exemptions_engine/declaration_forms/new.html.erb
  config/locales/forms/declaration_forms/en.yml
  config/routes.rb
  db/migrate/20190104133305_add_declaration_to_enrollments.rb
Labels: enhancement

#27 Add registration complete page
  app/controllers/waste_exemptions_engine/registration_complete_forms_controller.rb
  app/forms/waste_exemptions_engine/registration_complete_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/models/waste_exemptions_engine/enrollment.rb
  app/models/waste_exemptions_engine/enrollment_exemption.rb
  app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
  config/locales/forms/registration_complete_forms/en.yml
  config/routes.rb
  db/migrate/20190104151459_add_reference_to_enrollments.rb
  db/migrate/20190104153628_add_date_fields_to_enrollment_exemptions.rb
  db/migrate/20190104154234_add_status_to_enrollment_exemptions.rb
Labels: enhancement

#30 Fix copy for org. name and validtion header
  config/locales/forms/applicant_email_forms/en.yml
  config/locales/forms/applicant_name_forms/en.yml
  config/locales/forms/applicant_phone_forms/en.yml
  config/locales/forms/business_type_forms/en.yml
  config/locales/forms/check_your_answers_forms/en.yml
  config/locales/forms/contact_address_lookup_forms/en.yml
  config/locales/forms/contact_address_manual_forms/en.yml
  config/locales/forms/contact_email_forms/en.yml
  config/locales/forms/contact_name_forms/en.yml
  config/locales/forms/contact_phone_forms/en.yml
  config/locales/forms/contact_position_forms/en.yml
  config/locales/forms/declaration_forms/en.yml
  config/locales/forms/is_a_farm_forms/en.yml
  config/locales/forms/on_a_farm_forms/en.yml
  config/locales/forms/operator_address_lookup_forms/en.yml
  config/locales/forms/operator_address_manual_forms/en.yml
  config/locales/forms/operator_name_forms/en.yml
  config/locales/forms/registration_complete_forms/en.yml
  config/locales/forms/registration_number_forms/en.yml
  config/locales/forms/site_address_lookup_forms/en.yml
  config/locales/forms/site_address_manual_forms/en.yml
Labels: bug

#31 Fix broken company reg. no. in check your answers
  app/views/waste_exemptions_engine/check_your_answers_forms/new.html.erb
Labels: bug

#33 Fix broken company registration number page
  app/views/waste_exemptions_engine/registration_number_forms/new.html.erb
Labels: bug

#39 Add partners page
  app/controllers/waste_exemptions_engine/main_people_forms_controller.rb
  app/controllers/waste_exemptions_engine/person_forms_controller.rb
  app/forms/waste_exemptions_engine/main_people_form.rb
  app/forms/waste_exemptions_engine/person_form.rb
  app/models/concerns/waste_exemptions_engine/can_change_workflow_status.rb
  app/models/concerns/waste_exemptions_engine/can_have_registration_attributes.rb
  app/models/concerns/waste_exemptions_engine/can_limit_number_of_main_people.rb
  app/models/waste_exemptions_engine/person.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/transient_person.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
  app/validators/waste_exemptions_engine/main_person_validator.rb
  app/validators/waste_exemptions_engine/person_validator.rb
  app/views/waste_exemptions_engine/main_people_forms/new.html.erb
  app/views/waste_exemptions_engine/shared/_person_name.html.erb
  config/locales/forms/main_people_forms/en.yml
  config/routes.rb
  db/migrate/20190109170024_create_transient_people.rb
  db/migrate/20190109170443_create_people.rb
Labels: enhancement

#40 Send confirmation email when registration complete
  app/assets/images/waste_exemptions_engine/.keep
  app/assets/images/waste_exemptions_engine/govuk_logotype_email.png
  app/forms/waste_exemptions_engine/registration_complete_form.rb
  app/helpers/waste_exemptions_engine/mailer_helper.rb
  app/mailers/waste_exemptions_engine/confirmation_mailer.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
  app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
  app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
  config/locales/forms/registration_complete_forms/en.yml
  config/locales/mailers/confirmation_mailer.en.yml
Labels: enhancement

#42 Generate registration pdf & attach to conf. email
  .travis.yml
  Gemfile.lock
  app/assets/images/waste_exemptions_engine/environment_agency_logo.png
  app/helpers/waste_exemptions_engine/application_helper.rb
  app/mailers/waste_exemptions_engine/confirmation_mailer.rb
  app/presenters/waste_exemptions_engine/base_presenter.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  app/services/waste_exemptions_engine/generate_pdf_service.rb
  app/services/waste_exemptions_engine/registration_completion_service.rb
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
  config/initializers/time_formats.rb
  config/initializers/wickedpdf.rb
  config/locales/pdfs/certificate.en.yml
  db/migrate/20190121092357_add_submitted_at_to_registrations.rb
  script/wkhtmltopdf.sh
  waste_exemptions_engine.gemspec
Labels: enhancement

#43 Implement configuration in the engine
  app/mailers/waste_exemptions_engine/confirmation_mailer.rb
  app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  app/services/waste_exemptions_engine/address_finder_service.rb
  app/services/waste_exemptions_engine/companies_house_service.rb
  app/views/pages/version.html.erb
  app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
  config/initializers/wickedpdf.rb
  lib/waste_exemptions_engine.rb
Labels: housekeeping

#44 Improve exemptions dates in PDF certificate
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
  config/locales/pdfs/certificate.en.yml
Labels: bug

#45 Remove notice icon from declaration page
  app/views/waste_exemptions_engine/declaration_forms/new.html.erb
Labels: bug

#46 Fix site validation in check answers page
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
Labels: bug

#49 Fix broken rspec test environment
  .travis.yml
  Gemfile
  spec/dummy/db/schema.rb
  spec/factories/transient_registration.rb
  spec/models/waste_exemptions_engine/transient_registration_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/database_cleaner.rb
  spec/support/factory_bot.rb
  spec/support/vcr.rb
Labels: bug

#48 Convert to block style configuration
  app/mailers/waste_exemptions_engine/confirmation_mailer.rb
  app/models/concerns/waste_exemptions_engine/can_change_exemption_status.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  app/services/waste_exemptions_engine/address_finder_service.rb
  app/services/waste_exemptions_engine/companies_house_service.rb
  app/views/pages/version.html.erb
  app/views/waste_exemptions_engine/confirmation_mailer/send_confirmation_email.html.erb
  config/initializers/wickedpdf.rb
  lib/waste_exemptions_engine.rb
Labels: housekeeping

#50 Fix location of git_repository_url on version page
  app/views/pages/version.html.erb
Labels: bug
