Repository DEFRA/waste-exemptions-engine, pull requests merged in 2019-03, with the labels that each got.

#90 Fix typo on check details page
  config/locales/forms/check_your_answers_forms/en.yml
Labels: bug

#89 Add workflow tests
  spec/factories/address.rb
  spec/factories/transient_address.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/applicant_email_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/applicant_name_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/applicant_phone_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/business_type_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/check_your_answers_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_agency_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_email_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_name_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_phone_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_position_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/contact_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/declaration_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/exemptions_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/is_a_farmer_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/location_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/main_people_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/on_a_farm_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_name_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/operator_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/register_in_northern_ireland_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/register_in_scotland_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/register_in_wales_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/registration_complete_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/registration_number_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_address_lookup_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_address_manual_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_grid_reference_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/site_postcode_form_spec.rb
  spec/models/waste_exemptions_engine/transient_registration_workflow_state/start_form_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/workflow_states.rb
  spec/support/shared_examples/models/owner_of_registration_attributes.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_final_state.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_simple_bidirectional_transition.rb
Labels: housekeeping

#93 Refactor 'can navigate flexibly' form property
  app/controllers/waste_exemptions_engine/forms_controller.rb
  app/forms/waste_exemptions_engine/address_form.rb
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/applicant_name_form.rb
  app/forms/waste_exemptions_engine/applicant_phone_form.rb
  app/forms/waste_exemptions_engine/base_form.rb
  app/forms/waste_exemptions_engine/business_type_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_agency_form.rb
  app/forms/waste_exemptions_engine/contact_email_form.rb
  app/forms/waste_exemptions_engine/contact_name_form.rb
  app/forms/waste_exemptions_engine/contact_phone_form.rb
  app/forms/waste_exemptions_engine/contact_position_form.rb
  app/forms/waste_exemptions_engine/contact_postcode_form.rb
  app/forms/waste_exemptions_engine/declaration_form.rb
  app/forms/waste_exemptions_engine/exemptions_form.rb
  app/forms/waste_exemptions_engine/is_a_farmer_form.rb
  app/forms/waste_exemptions_engine/location_form.rb
  app/forms/waste_exemptions_engine/main_people_form.rb
  app/forms/waste_exemptions_engine/on_a_farm_form.rb
  app/forms/waste_exemptions_engine/operator_name_form.rb
  app/forms/waste_exemptions_engine/operator_postcode_form.rb
  app/forms/waste_exemptions_engine/register_in_northern_ireland_form.rb
  app/forms/waste_exemptions_engine/register_in_scotland_form.rb
  app/forms/waste_exemptions_engine/register_in_wales_form.rb
  app/forms/waste_exemptions_engine/registration_number_form.rb
  app/forms/waste_exemptions_engine/site_grid_reference_form.rb
  app/forms/waste_exemptions_engine/site_postcode_form.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/forms/waste_exemptions_engine/base_form_spec.rb
  spec/support/helpers/workflow_states.rb
Labels: housekeeping

#94 Use explicit reference to redirect constants
  app/controllers/waste_exemptions_engine/forms_controller.rb
Labels: bug

#95 Unlock Rails version
  Gemfile.lock
  waste_exemptions_engine.gemspec
Labels: housekeeping

#86 Implement PaperTrail for auditing
  Gemfile.lock
  app/controllers/waste_exemptions_engine/application_controller.rb
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/registration.rb
  db/migrate/20190228152336_create_versions.rb
  lib/waste_exemptions_engine.rb
  lib/waste_exemptions_engine/engine.rb
  spec/dummy/app/controllers/application_controller.rb
  spec/dummy/db/schema.rb
  spec/models/waste_exemptions_engine/address_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/requests/waste_exemptions_engine/registration_complete_forms_spec.rb
  spec/support/paper_trail.rb
  spec/support/shared_examples/models/has_paper_trail.rb
  waste_exemptions_engine.gemspec
Labels: enhancement

#100 Load engine migrations before host app migrations
  lib/waste_exemptions_engine/engine.rb
Labels: bug

#98 Save the assistance mode for a registration
  app/services/waste_exemptions_engine/registration_completion_service.rb
  db/migrate/20190314161232_add_assistance_mode_to_registrations.rb
  lib/waste_exemptions_engine.rb
  spec/dummy/db/schema.rb
  spec/services/waste_exemptions_engine/registration_completion_service_spec.rb
Labels: enhancement

#106 Add message column to registration exemption
  db/migrate/20190319133740_add_deregistration_message_to_registration_exemption.rb
  spec/cassettes/company_no_valid.yml
  spec/dummy/db/schema.rb
  spec/models/waste_exemptions_engine/transient_registration_exemption_spec.rb
  spec/support/helpers/model_properties.rb
Labels: enhancement

#110 Add deregistered_on to registration_exemptions
  db/migrate/20190326133420_add_deregistered_on_to_registration_exemption.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/dummy/db/schema.rb
  spec/support/helpers/model_properties.rb
Labels: enhancement
