Repository DEFRA/waste-exemptions-engine, pull requests merged in 2020-02, with the labels that each got.

#405 Use defra_ruby_address for address lookup
  Gemfile.lock
  app/forms/waste_exemptions_engine/address_lookup_form_base.rb
  app/services/waste_exemptions_engine/address_finder_service.rb
  app/services/waste_exemptions_engine/address_lookup_service.rb
  app/services/waste_exemptions_engine/determine_easting_and_northing_service.rb
  app/validators/waste_exemptions_engine/postcode_validator.rb
  lib/waste_exemptions_engine.rb
  lib/waste_exemptions_engine/engine.rb
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/dummy/config/initializers/waste_exemptions_engine.rb
  spec/services/waste_exemptions_engine/determine_easting_and_northing_service_spec.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#427 Switch airbrake mgmt to defra-ruby-alert
  Gemfile.lock
  lib/waste_exemptions_engine.rb
  lib/waste_exemptions_engine/engine.rb
  spec/dummy/config/initializers/waste_exemptions_engine.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#430 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_from_grid_ref_auto_area.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec/GET-confirm_edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec/GET-edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec/GET-edit_complete_form.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec/when-WasteExemptionsEngine-configuration-edit_enabled-is-true-.yml
  spec/cassettes/w3c_valid_content/errors_spec/-show.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/location_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec/GET-renew_with_changes_form.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec/GET-renew_without_changes_form.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/start_forms_spec/GET-start_form.yml
Labels: housekeeping

#431 Use defra-ruby-email for last email functionality
  Gemfile.lock
  app/controllers/waste_exemptions_engine/last_email_controller.rb
  app/services/waste_exemptions_engine/last_email_cache_service.rb
  config/routes.rb
  lib/waste_exemptions_engine.rb
  lib/waste_exemptions_engine/engine.rb
  spec/requests/waste_exemptions_engine/last_email_spec.rb
  spec/services/waste_exemptions_engine/last_email_cache_service_spec.rb
  waste_exemptions_engine.gemspec
Labels: housekeeping

#436 Bump defra_ruby_email from 0.1.0 to 0.2.0
  Gemfile.lock
Labels: dependencies

#438 Update VCR cassettes
  spec/cassettes/company_no_valid.yml
  spec/cassettes/postcode_no_matches.yml
  spec/cassettes/postcode_valid.yml
  spec/cassettes/site_address_from_grid_ref_auto_area.yml
  spec/cassettes/w3c_valid_content/applicant_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/applicant_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/business_type_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/confirm_edit_cancelled_forms_spec/GET-confirm_edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/contact_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_agency_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_email_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_phone_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_position_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/contact_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/declaration_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/edit_cancelled_forms_spec/GET-edit_cancelled_form.yml
  spec/cassettes/w3c_valid_content/edit_complete_forms_spec/GET-edit_complete_form.yml
  spec/cassettes/w3c_valid_content/edit_forms_spec/when-WasteExemptionsEngine-configuration-edit_enabled-is-true-.yml
  spec/cassettes/w3c_valid_content/errors_spec/-show.yml
  spec/cassettes/w3c_valid_content/exemptions_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/is_a_farmer_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/location_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/main_people_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/on_a_farm_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_name_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/operator_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_northern_ireland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_scotland_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/register_in_wales_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_complete_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/registration_number_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/cassettes/w3c_valid_content/renew_with_changes_forms_spec/GET-renew_with_changes_form.yml
  spec/cassettes/w3c_valid_content/renew_without_changes_forms_spec/GET-renew_without_changes_form.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/cassettes/w3c_valid_content/site_address_lookup_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_address_manual_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_grid_reference_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/site_postcode_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/start_forms_spec/GET-start_form.yml
Labels: housekeeping

#440 Fix visual bug on error message
  app/views/waste_exemptions_engine/start_forms/new.html.erb
Labels: bug
