Repository DEFRA/waste-exemptions-engine, pull requests merged in 2020-07, with the labels that each got.

#481 Update validator error message syntax with concern
  app/validators/concerns/waste_exemptions_engine/can_add_validation_errors.rb
  app/validators/concerns/waste_exemptions_engine/can_validate_length.rb
  app/validators/concerns/waste_exemptions_engine/can_validate_presence.rb
  app/validators/concerns/waste_exemptions_engine/can_validate_selection.rb
  app/validators/waste_exemptions_engine/address_validator.rb
  app/validators/waste_exemptions_engine/base_validator.rb
  app/validators/waste_exemptions_engine/exemptions_validator.rb
  app/validators/waste_exemptions_engine/manual_address_validator.rb
  app/validators/waste_exemptions_engine/matching_email_validator.rb
  app/validators/waste_exemptions_engine/person_name_validator.rb
  app/validators/waste_exemptions_engine/postcode_validator.rb
Labels: bug

#483 Update validation gem
  Gemfile.lock
  waste_exemptions_engine.gemspec
Labels: dependencies

#485 Update defra-ruby-alert
  Gemfile.lock
Labels: housekeeping

#480 Updgrade Feature Toggle to proper model
  app/models/waste_exemptions_engine/feature_toggle.rb
  bin/rails
  db/migrate/20200629141525_create_feature_toggle.rb
  spec/dummy/db/schema.rb
  spec/factories/feature_toggle.rb
  spec/models/waste_exemptions_engine/feature_toggle_spec.rb
Labels: enhancement
