Repository DEFRA/waste-exemptions-engine, pull requests merged in 2022-07, with the labels that each got.

#680 Changing the renewals journey for CH number
  app/controllers/waste_exemptions_engine/renews_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  app/views/waste_exemptions_engine/check_registered_name_and_address_forms/new.html.erb
  spec/cassettes/w3c_valid_content/check_registered_name_and_address_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-registration-is-past-the-renewal-window.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-has-already-been-used.yml
  spec/cassettes/w3c_valid_content/renew_spec/when-a-token-is-invalid.yml
  spec/factories/forms/check_registered_name_and_address_form.rb
  spec/forms/waste_exemptions_engine/check_site_address_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/business_type_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/check_registered_name_and_address_forms_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/operator_name_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/registration_number_form_spec.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/renewal_start_form_spec.rb
  spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb
  spec/requests/waste_exemptions_engine/renew_spec.rb
Labels: enhancement

#681 Company house inactive error
  app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
  app/forms/waste_exemptions_engine/check_registered_name_and_address_form.rb
  app/views/waste_exemptions_engine/check_registered_name_and_address_forms/inactive_company.html.erb
  config/locales/forms/check_registered_name_and_address_forms/en.yml
  lib/defra_ruby_companies_house.rb
  spec/cassettes/w3c_valid_content/check_registered_name_and_address_forms_spec/when-the-company-status-is-no-longer-active.yml
  spec/fixtures/files/inactive_companies_house_response.json
  spec/lib/defra_ruby_companies_house_spec.rb
  spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb
Labels: enhancement

#683 Added db migration for companies_house_updated_at
  db/migrate/20220705144056_companies_house_updated_at_added_to_transient_registration.rb
  spec/dummy/db/schema.rb
Labels: bug

#682 Added in company house down page for API issues
  app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
  app/forms/waste_exemptions_engine/check_registered_name_and_address_form.rb
  app/views/waste_exemptions_engine/check_registered_name_and_address_forms/companies_house_down.html.erb
  config/locales/forms/check_registered_name_and_address_forms/en.yml
  spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb
Labels: enhancement

#686 Change to back navigation for renewals
  app/models/concerns/waste_exemptions_engine/can_use_renewing_registration_workflow.rb
  spec/models/waste_exemptions_engine/renewing_registration_workflow_state/operator_postcode_form_spec.rb
Labels: bug

#690 Optional applicant and contact email addresses
  app/controllers/waste_exemptions_engine/applicant_email_forms_controller.rb
  app/controllers/waste_exemptions_engine/contact_email_forms_controller.rb
  app/forms/waste_exemptions_engine/applicant_email_form.rb
  app/forms/waste_exemptions_engine/check_your_answers_form.rb
  app/forms/waste_exemptions_engine/contact_email_form.rb
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  app/validators/waste_exemptions_engine/optional_email_form_validator.rb
  app/validators/waste_exemptions_engine/optional_email_validator.rb
  app/views/waste_exemptions_engine/applicant_email_forms/new.html.erb
  app/views/waste_exemptions_engine/contact_email_forms/new.html.erb
  config/locales/forms/applicant_email_forms/en.yml
  config/locales/forms/contact_email_forms/en.yml
  lib/waste_exemptions_engine.rb
  spec/forms/waste_exemptions_engine/applicant_email_form_spec.rb
  spec/forms/waste_exemptions_engine/check_your_answers_form_spec.rb
  spec/forms/waste_exemptions_engine/contact_email_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/check_contact_phone_form_spec.rb
  spec/models/waste_exemptions_engine/new_registration_workflow_state/contact_phone_form_spec.rb
  spec/support/shared_examples/forms/optional_email_form.rb
  spec/support/shared_examples/models/transient_registration_workflow_state/a_simple_bidirectional_transition.rb
  spec/validators/waste_exemptions_engine/optional_email_form_validator_spec.rb
  spec/validators/waste_exemptions_engine/optional_email_validator_spec.rb
Labels: enhancement

#691 Companies House number validation
  app/controllers/waste_exemptions_engine/check_registered_name_and_address_forms_controller.rb
  spec/cassettes/w3c_valid_content/check_registered_name_and_address_forms_spec/when-the-company-number-is-invalid.yml
  spec/requests/waste_exemptions_engine/check_registered_name_and_address_forms_spec.rb
Labels: enhancement

#692 Inactive company content change
  app/views/waste_exemptions_engine/check_registered_name_and_address_forms/inactive_company.html.erb
  config/locales/forms/check_registered_name_and_address_forms/en.yml
Labels: enhancement

#693 Merge partner renewal hotfix into main
  app/forms/waste_exemptions_engine/main_people_form.rb
  app/validators/waste_exemptions_engine/main_person_form_validator.rb
  spec/forms/waste_exemptions_engine/main_people_form_spec.rb
  spec/requests/waste_exemptions_engine/main_people_forms_spec.rb
Labels: housekeeping
