Repository DEFRA/waste-exemptions-engine, pull requests merged in 2023-10, with the labels that each got.

#864 Return HTTP 404 instead of 422 for an expired edit_token
  app/controllers/waste_exemptions_engine/front_office_edit_forms_controller.rb
  spec/requests/waste_exemptions_engine/front_office_edit_forms_spec.rb
Labels: bug

#865 Update content on choose exemptions page
  config/locales/forms/exemptions_forms/en.yml
Labels: enhancement

#868 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#873 Add unhandled exception logging
  app/controllers/waste_exemptions_engine/application_controller.rb
  spec/requests/waste_exemptions_engine/forms_spec.rb
Labels: housekeeping

#874 Revert "Add unhandled exception logging (#873)"
  app/controllers/waste_exemptions_engine/application_controller.rb
  spec/requests/waste_exemptions_engine/forms_spec.rb
Labels: bug, housekeeping

#877 Fix/ruby 2728 exemption status on cert
  app/models/concerns/waste_exemptions_engine/can_iterate_exemptions.rb
  app/presenters/waste_exemptions_engine/certificate_presenter.rb
  app/presenters/waste_exemptions_engine/registration_details_presenter.rb
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
  config/locales/pdfs/certificate.en.yml
  spec/presenters/waste_exemptions_engine/certificate_presenter_spec.rb
Labels: enhancement

#878 Fix/ruby 2728 exemption status on cert
  app/views/waste_exemptions_engine/pdfs/certificate.html.erb
Labels: enhancement
