Repository DEFRA/waste-exemptions-engine, pull requests merged in 2023-07, with the labels that each got.

#826 Show only active registrations on the renewal page
  app/views/waste_exemptions_engine/renew_exemptions_forms/new.html.erb
Labels: bug

#827 Feature/ruby 2322 wex remove t 27 exemption from choose exemptions page
  app/helpers/waste_exemptions_engine/exemptions_forms_helper.rb
  app/models/waste_exemptions_engine/exemption.rb
  app/views/waste_exemptions_engine/exemptions_forms/new.html.erb
  db/migrate/20230703114724_add_hidden_field_to_exemptions.rb
  spec/dummy/db/schema.rb
  spec/helpers/waste_exemptions_engine/exemptions_forms_helper_spec.rb
  spec/support/factories/exemption.rb
Labels: enhancement

#828 add registration complete survey link
  app/views/waste_exemptions_engine/registration_complete_forms/new.html.erb
  app/views/waste_exemptions_engine/renewal_complete_forms/new.html.erb
  config/locales/forms/registration_complete_forms/en.yml
  spec/cassettes/w3c_valid_content/renewal_complete_forms_spec/GET-renewal_complete_form.yml
Labels: bug

#830 fix/skip_to_address
  app/controllers/waste_exemptions_engine/site_grid_reference_forms_controller.rb
  config/locales/forms/deregistration_complete_full_forms/en.yml
  config/locales/forms/deregistration_complete_no_change_forms/en.yml
  config/locales/forms/deregistration_complete_partial_forms/en.yml
  config/locales/forms/edit_cancelled_forms/en.yml
  config/locales/forms/edit_complete_forms/en.yml
  config/locales/forms/registration_complete_forms/en.yml
  spec/requests/waste_exemptions_engine/transient_registration_spec.rb
Labels: bug

#831 Feature/ruby 2841 comms history
  README.md
  db/migrate/20230627104104_remove_deregistration_email_sent_at.rb
  spec/dummy/db/schema.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: enhancement

#832 Drop remove_deregistration_email_sent_at migration
  db/migrate/20230627104104_remove_deregistration_email_sent_at.rb
Labels: bug

#833 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping
