Repository DEFRA/waste-exemptions-engine, pull requests merged in 2024-06, with the labels that each got.

#1004 [RUBY-3195] Hiding change links on CYA page for renewals
  app/views/waste_exemptions_engine/shared/data_overview/_company_info.html.erb
  app/views/waste_exemptions_engine/shared/data_overview/_registration_info.html.erb
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
Labels: bug

#1009 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1011 Feature/ruby 3121 cya on farm
  Gemfile
  Gemfile.lock
  app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
  app/controllers/waste_exemptions_engine/person_forms_controller.rb
  app/forms/waste_exemptions_engine/check_contact_address_form.rb
  app/forms/waste_exemptions_engine/check_contact_email_form.rb
  app/forms/waste_exemptions_engine/check_contact_name_form.rb
  app/forms/waste_exemptions_engine/check_contact_phone_form.rb
  app/forms/waste_exemptions_engine/check_registered_name_and_address_form.rb
  app/forms/waste_exemptions_engine/check_site_address_form.rb
  app/forms/waste_exemptions_engine/renewal_start_form.rb
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  app/models/waste_exemptions_engine/new_registration.rb
  app/presenters/waste_exemptions_engine/data_overview_presenter.rb
  app/validators/waste_exemptions_engine/main_person_form_validator.rb
  config/locales/partials/data_overview/registration_info.en.yml
  config/routes.rb
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/presenters/waste_exemptions_engine/data_overview_presenter_spec.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_exemptions_engine/on_a_farm_forms_spec.rb
  spec/spec_helper.rb
  spec/support/factories/forms/on_a_farm_form.rb
  spec/validators/waste_exemptions_engine/manual_address_validator_spec.rb
Labels: enhancement

#1013 Feature/ruby 3122 wex charging check your answers page change are these exemptions used for a farmer or a farming business
  app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  app/presenters/waste_exemptions_engine/data_overview_presenter.rb
  config/locales/partials/data_overview/registration_info.en.yml
  config/routes.rb
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/presenters/waste_exemptions_engine/data_overview_presenter_spec.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_exemptions_engine/is_a_farmer_forms_spec.rb
  spec/support/factories/forms/is_a_farmer_form.rb
Labels: enhancement

#1015 raise an error when no exemptions selected ON CYA change exemptions flow
  app/forms/waste_exemptions_engine/exemptions_form.rb
  spec/requests/waste_exemptions_engine/exemptions_forms_spec.rb
Labels: bug

#1016 [RUBY-3123] feat: Add ability to edit applicant name, phone, and email on check your answers page
  app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  app/presenters/waste_exemptions_engine/data_overview_presenter.rb
  config/locales/partials/data_overview/registration_info.en.yml
  config/routes.rb
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/presenters/waste_exemptions_engine/data_overview_presenter_spec.rb
  spec/requests/waste_exemptions_engine/applicant_email_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_name_forms_spec.rb
  spec/requests/waste_exemptions_engine/applicant_phone_forms_spec.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/support/factories/forms/applicant_email_form.rb
  spec/support/factories/forms/applicant_name_form.rb
  spec/support/factories/forms/applicant_phone_form.rb
Labels: enhancement

#1018 [RUBY-3114] feat: Add ability to edit operator address on check your answers page
  app/controllers/waste_exemptions_engine/check_your_answers_forms_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_new_registration_workflow.rb
  app/presenters/waste_exemptions_engine/data_overview_presenter.rb
  config/locales/partials/data_overview/company_info.en.yml
  config/routes.rb
  spec/cassettes/w3c_valid_content/check_your_answers_forms_spec/when-the-registration-is-in-the-correct-state.yml
  spec/cassettes/w3c_valid_content/renewal_start_forms_spec/GET-renewal_start_form.yml
  spec/presenters/waste_exemptions_engine/data_overview_presenter_spec.rb
  spec/requests/waste_exemptions_engine/check_your_answers_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_address_lookup_forms_spec.rb
  spec/requests/waste_exemptions_engine/operator_address_manual_forms_spec.rb
  spec/support/factories/forms/operator_address_lookup_form.rb
  spec/support/factories/forms/operator_address_manual_form.rb
Labels: enhancement
