Repository DEFRA/waste-exemptions-engine, pull requests merged in 2024-01, with the labels that each got.

#907 making shared back link template label configurable
  app/views/waste_exemptions_engine/shared/_back.html.erb
Labels: enhancement

#913 Fix/ruby 2805 postcode validation
  app/forms/waste_exemptions_engine/contact_postcode_form.rb
  app/forms/waste_exemptions_engine/operator_postcode_form.rb
  app/forms/waste_exemptions_engine/site_postcode_form.rb
  app/validators/concerns/waste_exemptions_engine/can_add_validation_errors.rb
  app/validators/waste_exemptions_engine/address_lookup_validator.rb
  spec/dummy/config/locales/postcode_validator/en.yml
  spec/validators/waste_exemptions_engine/postcode_validator_spec.rb
Labels: housekeeping

#914 [RUBY-2785] ability to edit contact address
  app/controllers/waste_exemptions_engine/front_office_edit_forms_controller.rb
  app/models/concerns/waste_exemptions_engine/can_use_front_office_edit_registration_workflow.rb
  app/models/waste_exemptions_engine/front_office_edit_registration.rb
  app/services/waste_exemptions_engine/front_office_edit_completion_service.rb
  app/views/waste_exemptions_engine/front_office_edit_forms/new.html.erb
  config/locales/forms/front_office_edit_forms/en.yml
  config/routes.rb
  spec/models/waste_exemptions_engine/front_office_edit_registration_spec.rb
  spec/models/waste_exemptions_engine/front_office_edit_registration_workflow_state/front_office_edit_form_spec.rb
  spec/requests/waste_exemptions_engine/front_office_edit_forms_spec.rb
  spec/services/waste_exemptions_engine/front_office_edit_completion_service_spec.rb
Labels: enhancement

#918 Add SafeCopyRegistrationAttributesService
  Gemfile.lock
  app/models/waste_exemptions_engine/transient_registration.rb
  app/services/waste_exemptions_engine/safe_copy_registration_attributes_service.rb
  spec/services/waste_exemptions_engine/safe_copy_registration_attributes_service_spec.rb
Labels: housekeeping

#920 Fix/ruby 2852 comms record type
  app/services/waste_exemptions_engine/notify_confirmation_letter_service.rb
  app/services/waste_exemptions_engine/registration_edit_link_email_service.rb
  spec/support/shared_examples/models/can_have_communication_log.rb
Labels: bug
